USE [master]
GO

/****** Object:  Database [Eventter]    Script Date: 4/21/2019 6:43:35 PM ******/
CREATE DATABASE [Eventter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Eventter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Eventter.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Eventter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Eventter_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Eventter] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Eventter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Eventter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Eventter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Eventter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Eventter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Eventter] SET ARITHABORT OFF 
GO

ALTER DATABASE [Eventter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Eventter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Eventter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Eventter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Eventter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Eventter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Eventter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Eventter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Eventter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Eventter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Eventter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Eventter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Eventter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Eventter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Eventter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Eventter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Eventter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Eventter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Eventter] SET  MULTI_USER 
GO

ALTER DATABASE [Eventter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Eventter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Eventter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Eventter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Eventter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Eventter] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Eventter] SET  READ_WRITE 
GO

